# Generated by Django 4.0.3 on 2022-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('borough', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
