# Generated by Django 4.0.3 on 2022-04-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
