# Generated by Django 4.0.3 on 2022-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0002_crime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='time',
        ),
    ]
